### ISSUE TITLE
isEnrolledChallengeHandler.swift - uncaught exception

### ISSUE THREAD

**Issue by pahoran** [MobileFirst-Platform-Developer-Center/EnrollmentSwift#1]
This line is bombing in my tests:
`let userDisplayName = success["user"]!["displayName"] as! String`

> IsEnrolledChallengeHandler: handleSuccess - [:]
> fatal error: unexpectedly found nil while unwrapping an Optional value

This happens when clicking the "Unenroll" button in the native app.

**Comment by IdanAdar** [comment]
We are unable to reproduce this error, however we did commit updates to both the app and the Enrollment security check. Please update and try again.

If the issue continues to happen to you, please also mention your Xcode version and Swift version.

**Comment by IdanAdar** [comment]
Please comment to re-open the issue if this still happens.
